### ISSUE TITLE
Request for continuing this project

### ISSUE THREAD

**Issue by goxr3plus** [JoshSchreuder/SMSnatcher#9]
Hello friend i will use this awesome library with XR3Player :)  https://github.com/goxr3plus/XR3Player

I will contribute on the continuation of this awesome project :)

**Comment by JoshSchreuder** [comment]
Hey, I haven't done any Java dev in about 8 years :)

This code is MIT licensed so you're welcome to take it and do whatever you want with it, but I can't support it anymore, sorry!

**Comment by goxr3plus** [comment]
Sorry to hear that but glad that you answer :)
